server:
  port: 6543

spring:
  profiles:
    active: dev

  # 测试时，控制台彩色日志
  output:
    ansi:
      enabled: always
# mybatis-plus 相关配置
mybatis-plus:
  type-aliases-package: cn.jxwxkj.business.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml
  # mybatis-plus 的全局配置
  global-config:
    banner: false
  # mybatis 原生配置
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
logging:
  level:
    cn.jxwxkj: info

ali:
  oss:
    accessKeyId: LTAI4FqsSbxAqQcfKyTfPheU
    accessKeySecret: iGFEJYhfUjtJPXWsWuU3wGmRJ9dCBy
    bucketName: wcx-file
    endpoint: oss-cn-beijing.aliyuncs.com
